### ISSUE TITLE
How to use use with Vue CLI?

### ISSUE THREAD

**Issue by louisameline** [vue-perf-devtool/vue-perf-devtool#13]
Hello, silly question maybe, but how do I use this with Vue CLI? I am using Quasar with Vue CLI. Thank you.

**Comment by MinosIE** [comment]
what sence ?
I think it is just a performance analysis tool.

**Comment by louisameline** [comment]
I'm sorry, I don't even remember why I needed this or what it does. And I can't spend time on it anymore, so I'll close this issue. Thanks
