### ISSUE TITLE
Identifier 'o' has already been declared.

### ISSUE THREAD

**Issue by duebbert** [vue-perf-devtool/vue-perf-devtool#2]
I get an error on every page after installing this in Chrome:
```
content_script_bundle.js:1 Uncaught SyntaxError: Identifier 'o' has already been declared
    at s (content_script_bundle.js:1)
    at content_script_bundle.js:1
    at content_script_bundle.js:19
    at s (content_script_bundle.js:1)
    at o (content_script_bundle.js:1)
    at Object.<anonymous> (content_script_bundle.js:1)
    at content_script_bundle.js:19
    at content_script_bundle.js:1
    at Object.<anonymous> (content_script_bundle.js:19)
    at Object.1134 (content_script_bundle.js:19)
```

**Comment by rafaesc** [comment]
I saw that that error, too. But the problem was in the ghostery extension after that I disabled that extension, the error disappeared.
Try to uninstall vue performance devtool and tell me if the error is still there.

Regards

**Comment by duebbert** [comment]
Yes, sorry, I tried to reproduce it but the error is not showing anymore. Maybe it was connected with a different extension.
