### ISSUE TITLE
Installing vue-perf-devtool breaks Vuex pane of vue-devtools

### ISSUE THREAD

**Issue by viamin** [vue-perf-devtool/vue-perf-devtool#7]
This was reported in the vue-devtools repo as well here: https://github.com/vuejs/vue-devtools/issues/612

Installing this extension in Chrome breaks the Vuex pane of Vue-Devtools, showing "No Vuex store detected." The fix is to uninstall this extension.

**Comment by rafaesc** [comment]
Hi @viamin,

Thanks for reporting it, I will work on that.

**Comment by rafaesc** [comment]
Fixed it.

Out in 0.0.6!
